/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'john' at '9/05/15 11:10 PM' with Gradle 2.4
 *
 * @author john, @date 9/05/15 11:10 PM
 */
class Library {
    def importantMap() {
        [trueValue: false]
    }
}
