/*
 * This Spock specification was auto generated by running 'gradle init --type groovy-library'
 * by 'john' at '9/05/15 11:10 PM' with Gradle 2.4
 *
 * @author john, @date 9/05/15 11:10 PM
 */

import spock.lang.Specification

class LibraryTest extends Specification{
    def "someLibraryMethod returns true"() {
        setup:
        Library lib = new Library()
        when:
        def result = lib.someLibraryMethod()
        then:
        result == true
    }
}
